### ISSUE TITLE
kubernetes don't work

### ISSUE THREAD

**Issue by pablorsk** [richarvey/nginx-php-fpm#206]
Following your [Kubernetes guide](https://github.com/richarvey/nginx-php-fpm/blob/master/docs/guides/kubernetes.md) example-app pod never start, I receive this error:

```
Back-off restarting failed container
Error syncing pod
```

Also I need apply a fix on `example-service.yml`:
```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: example
  name: example-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  selector:
    app: example-app
```
